# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

circular_objective_cpp <- function(X, mu, weights) {
    .Call('_CausalMetricSpaces_circular_objective_cpp', PACKAGE = 'CausalMetricSpaces', X, mu, weights)
}

circular_frechet_mean_cpp <- function(X, weights, sorted) {
    .Call('_CausalMetricSpaces_circular_frechet_mean_cpp', PACKAGE = 'CausalMetricSpaces', X, weights, sorted)
}

circular_local <- function(y, K0, K1, A) {
    .Call('_CausalMetricSpaces_circular_local', PACKAGE = 'CausalMetricSpaces', y, K0, K1, A)
}

dist_cpp <- function(w1, w2) {
    .Call('_CausalMetricSpaces_dist_cpp', PACKAGE = 'CausalMetricSpaces', w1, w2)
}

circular_local_linear_cpp <- function(y0, y1, K0, K1, K0_means, K1_means, dist1_0, dist2_0, dist1_1, dist2_1, A) {
    .Call('_CausalMetricSpaces_circular_local_linear_cpp', PACKAGE = 'CausalMetricSpaces', y0, y1, K0, K1, K0_means, K1_means, dist1_0, dist2_0, dist1_1, dist2_1, A)
}

circular_local_linear_loo_cpp <- function(y, K0, K1, dist1, dist2, A) {
    .Call('_CausalMetricSpaces_circular_local_linear_loo_cpp', PACKAGE = 'CausalMetricSpaces', y, K0, K1, dist1, dist2, A)
}

circular_local_loo <- function(y, K0, K1, A) {
    .Call('_CausalMetricSpaces_circular_local_loo', PACKAGE = 'CausalMetricSpaces', y, K0, K1, A)
}

