# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

circular_objective_cpp <- function(X, mu, weights) {
    .Call('_CausalMetricSpaces_circular_objective_cpp', PACKAGE = 'CausalMetricSpaces', X, mu, weights)
}

circular_frechet_mean_cpp <- function(X, weights, sorted) {
    .Call('_CausalMetricSpaces_circular_frechet_mean_cpp', PACKAGE = 'CausalMetricSpaces', X, weights, sorted)
}

circular_local <- function(y, K0, K1, A) {
    .Call('_CausalMetricSpaces_circular_local', PACKAGE = 'CausalMetricSpaces', y, K0, K1, A)
}

dist_cpp <- function(w1, w2) {
    .Call('_CausalMetricSpaces_dist_cpp', PACKAGE = 'CausalMetricSpaces', w1, w2)
}

circular_local_linear_cpp <- function(y0, y1, K0, K1, K0_means, K1_means, dist1_0, dist2_0, dist1_1, dist2_1, A) {
    .Call('_CausalMetricSpaces_circular_local_linear_cpp', PACKAGE = 'CausalMetricSpaces', y0, y1, K0, K1, K0_means, K1_means, dist1_0, dist2_0, dist1_1, dist2_1, A)
}

circular_local_linear_loo_cpp <- function(y, K0, K1, dist1, dist2, A) {
    .Call('_CausalMetricSpaces_circular_local_linear_loo_cpp', PACKAGE = 'CausalMetricSpaces', y, K0, K1, dist1, dist2, A)
}

circular_local_loo <- function(y, K0, K1, A) {
    .Call('_CausalMetricSpaces_circular_local_loo', PACKAGE = 'CausalMetricSpaces', y, K0, K1, A)
}

distance_gaussian_cpp <- function(Sigma0, Sigma1) {
    .Call('_CausalMetricSpaces_distance_gaussian_cpp', PACKAGE = 'CausalMetricSpaces', Sigma0, Sigma1)
}

frechet_mean_gaussian_cpp <- function(Sigma, weights, max_iter, tol) {
    .Call('_CausalMetricSpaces_frechet_mean_gaussian_cpp', PACKAGE = 'CausalMetricSpaces', Sigma, weights, max_iter, tol)
}

bw_local <- function(mu, Sigma, K0, K1, A, max_iter, tol) {
    .Call('_CausalMetricSpaces_bw_local', PACKAGE = 'CausalMetricSpaces', mu, Sigma, K0, K1, A, max_iter, tol)
}

bw_local_loo <- function(mu, Sigma, K0, K1, A, max_iter, tol) {
    .Call('_CausalMetricSpaces_bw_local_loo', PACKAGE = 'CausalMetricSpaces', mu, Sigma, K0, K1, A, max_iter, tol)
}

